apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    "operatorframework.io/suggested-namespace": openshift-logging
    alm-examples: |-
      [
        {
          "apiVersion": "grafana.example.com/v1alpha1",
          "kind": "GrafanaCloudLogForwarder",
          "metadata": {
            "name": "grafanacloudlogforwarder-sample",
            "namespace": "openshift-logging"
          },
          "spec": {
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.12.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: grafanacloud-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: GrafanaCloudLogForwarder
      description: GrafanaCloudLogForwarder is the Schema for the grafanacloudlogforwarders API
      displayName: Grafana Cloud Log Forwarder
      name: grafanacloudlogforwarders.grafana.example.com
      version: v1alpha1
      specDescriptors:
      - displayName: URL
        description: URL of loki datasource
        path: url
        x-descriptors:
          - 'urn:alm:descriptor:com.tectonic.ui:text'
      - displayName: Username
        description: The username from the loki endpoint
        path: username
        x-descriptors:
          - 'urn:alm:descriptor:com.tectonic.ui:text'
      - displayName: Password
        description: API password for accessing loki datasource
        path: apipassword
        x-descriptors:
          - 'urn:alm:descriptor:com.tectonic.ui:password'
  description: MVP for forwarding clusterlogs to Loki datasource on Grafana Cloud
  displayName: GrafanaCloudLog
  icon:
  - base64data: "iVBORw0KGgoAAAANSUhEUgAAAi4AAABaCAMAAACouC0TAAABmFBMVEX///8KCgoAAADwWij4tBD5tw/5uQ7zfx7zgh30hRz5uw4FBQX2mxb1lBj1kRn3phP4sBDzeh/b29urq6vx8fGFhYX4rRHxaSOLi4tubm7/+/FFRUWcnJz0iRsTExPxbSL6wxfydCD3oxQzMzMhISHwYCbycCH5xFHX19fGxsb++fXwVR6UlJTm5ubZ2dmnp6e7u7v1kADycgV5eXlaWlrzewAsLCxjY2P0j285OTlTU1O1tbX96+X3saJra2v4wJ/0hQDvTQDwYADvWhP85tr0j0n6zan71qf85tD85br6x2P72c/5x7jyc03wYDDzf172o4vxZwD2oG/0hTD3rG397Nr5w4f3pz/72bb2o0T605385LT84KX60XP70lz+9NX1lXjxbD/4vKr0lHHycDL2q5bydkD1ooTzgVDzgEv0jl/61ML5x6z2qXv1kU/zfDn2pG74tpP1mEv3rGf0kTP4uXf5yZX4tWv3pCz5xob2o1D5w3n2ojr4s0b4tVX4ti772JH5vzj72Ib6z1X6yTn82HL6yw/98ciL9QIsAAAXI0lEQVR4nO2d+0MSWRvHcczaxLIQDBHJVdZgAAUVSWVV1MxrZWZrqdlle3dLra2tNMu8bL3+2+/MnPttBghWe+X7w24z55lzDpwPz3nObXS5CpH+/PZMQQ9UdIqVvZ6LVf963LWo6MdQ9lasuro6dv2461HRj6DsnEmLwctj/birUtGJl34b0GLwcue461LRiddjREt1dW72uCtT0QnXbDVRbC573NWp6ESLdEUWL5XhUUV2mqFpqa5+ctz1qehEa47FJfZ8JkuNj7LjMzOV+buKkGaqOcViT27fmbWI0Z8+nrsVy8Uq8UxFhvTxO7d4WgAxserr69nnt8x/mA7nuCta0QnQ+vVYTEYLQCb3BM/G3K64l9MnHQlcztyuVsPC6lYlejllys7+en3uVi6XsyKTcVf2sY1n4VWZvDtdWr/+pDqG+IiZwexc/rBUJmNOmdYFT1KAa6ngcto060wEoigWk5BUGRqdKuWBSyyWq37y5LapOarjAsoVHOp6ItGgvyfT5AtGIx5vOT7Tjyv9+XWgk7pbZEY6u8KwMndndmYmaw2czIncO3M5ipgC9zUkgj19GlFfJt5Zpg/2Q0q/Dpx47sfEJfbk+lOx5tmnt29hYHL590aJrn6TkSoi87I5WXExSAYu4Es9qbiM2+ASu/V8XPHYzJ0cBuZpfiUl4oZfcVfxchvADJbs4zhUoTOKlfiXyixIpcVF/xWohHMd+pwaFtv9ltnHaCovllf4MtjH+BVaBjD/Qpfk8TX3hUNYyfKXWLhKjMsvuTFDuVLum72tGDfH5pwomIWPxp44LwQkmpSwAGD8Ze6Roj1WsOSG0ppPZA+oPxv7xVSJcPndymyslLjckeMSe+zMgH4HxLyxP5wsO9tZWNwa1y+5td6y9g4NIbY8LVjO0orWycdlJielJb8AdhasNTqtBHQJ8W24vy/EIqNVlTGC4X2bWytfWd+j8uDyRwlx0ccktOTyHR7P/GJtY3hiW6EG0ljWUCgejXgSns5IwxA9UNLK94uP8x2h5itXUd8nhMvYicVF1hvl8p/Zz9523PYSp5AI97AhZqQpjF2M1lOmeKJLoCUcKU9J3ysDlyumRkuEi5VZaXGZFXAp6MiidcrRLtodxLQYAa3YTBE/TNf6ykSLt08jERNQpjwlfbd+AFx0fmxU4AmRcTN+UbuXSBVurF75cNmTMYHR+soV6/o1RGum60TOthDpz66UHpfRkuLims39wii3XtjzMzGzg1QkeptxY8WV3iMYNn7x0cJKzV/90HuFGspVQslUYlxeg9xKi4vrzzGaljF5V6Trs0+fG5rN6nzpz43nVYOjIUSLbWMl+rWuoqqehyJhqwrukzkxx0q/e9VSqXCxMpsvMS7jv9O4/C6b+F9//p8xqNzvz55yvdX1sV/GnkmzjuKeyL6xEmWjBQW62lDZSiid9LsdluZLhYuV2WaJV6D+oNzLmGTObeblFdoBjY395xnDlMnbC1nAk4BdkfsYp8WCEJeydXYlVKlx6SgHLtk/r1ASnEv22ejYFU5juWf0GsGbsStjsogHDWGPc54DTrpoJ3LWn1OJcVmwMusuMS4zNAgvhdQXAiwWMFeolWj96pVR2cJ0GDbVcbaV/4fCpftnU6XCxcqs1LgMjxIKRnknsT4qg8UyfUn6n9lRkTNzOhd2ReXsCBKeiKFO5cY8H8TFNhNvwswk4slvoA2sO/MwhpVL5MkqwqU7vwbOjs9sDA8Pr4/js8h61hK45HHJjo8PW+bj6uxBluszNiYvKQZ+50KQ9asqWgxe/sQdV/bFlddixpnviTITcb8hn0VaosG6AGKMunqaw+bSQqg944dQRnzkQRfBxUdy8HFxd9TX22/O4VWFB3oaQMt6gSEOuRp8+NITz1jWoWZkrJCHVG4IVS7KVo6TgctlU/ngom9svrrcDXTj7gZot/WFG6Y2gMUCyAzgskTMF+4OL0rznMQ2l19tquZT5q9izXOBbrYDpXS8/vPlyxevOyjjq1dfY17ezI8K+UbAdGqRzsUDdml2ubzJfjIfq2kEF2+0F+xKQDO2fUGz+QaBHWppH574keVhYhkCWxtgJu6Mx8wbGPYjK2t5y9z24OmF1m5rWd2vdDFC5brMygVBvopZBf2vfHHJDhvtehnLaOBNsy3WrXvdAi768AJrfvmVOADO3rhM21xeGJYNX8ZHO5Cuzm+waS/nrdsd83fXTfekj68PvzaAweYv0OfKjo4KeQ/C33U/n5CXPNamB20w0kyvXGshDzLozAi7IKyNeaBYARd6zShOijGnCPlcfF6XN2Te1JqRWZNVmYGEj7XWtLB8IT3SJGY7kETB//fiYrb+ZU7d54Z1iMvlCWCFcHFNvhLN05tcg22cE2wWNsSKbMxjXDpez8iS5l9RjknfeEEeIIO0G0LU4+qBuBQ3pwJwqWoOM82t9aD0YEiylVMz0gvBJTIg2bbl1vqjclza+4UyNVIjSkblhGzNNTNHXNLnTDngkn0FzDil/wqsd1v/QriA25vD52T26QWmxSYkNulXYuGb80Y81GEGRR0dL5h66q86rJRN7kO9MSzhM/Nv4M0NARdvO+yLiluogbhwzYk6Nm+PfHueW8vE88clqtjjp4WCYQkufGVgicJKundIVbkhf164pG1xGT8vpcV47O0bKyUNcXkHbv+kMD/30zDJdF2aoSTEufszETu8We8GkbXwCEgAcTd0aePzw5yRFzqXgeKGsJ522Q+0D6b2KvdyapZfEHFxEyFcBqtUuRjhaZUEF4UxN6vktalc2G2Ly730T6ZscZlc+MlJCBcnuzRuM/0tvkf+m34jFK5vvCa0cGS8su5JHJJRZfzIXZjPMB87RSAufuHpvCTgQsWITIPA8BVfg+6Cx4WJOAAug/RDXCbQUIELDmLhJdP6eFWVVI6YuiUPEOWDy+II3d6WeArOQ1xaBDx4c8zLErybfjsxubg4ubT51rjxVghHs3fpIKib8RC6dW9Benhkff5n8MjP8nQXnnURQ5cINaaVCXyXDC7mdx4Kh0PtoGPza1RCOOMLBgequMbmcdGinREsK5fOMJ1Lc1Mw6OvnM5HhYpAV7onHh4itFqYdKFO59qZ4sGeAJ9EGl/OmbHAJ7JxHSqdH3k+Mj69/2Emnz9MaQbgwd9Pplr8nltYn3rdQ5iOTINu/4eVmAJaTXWrpnuALH+5mQmbWYKJbIIhoEz0o6auA0GKNMHRo0Ow1YFlRuLi1AWaGo4E0SHscRUYeH+OOBFyEAKMPt7bWhCdiGpjYV4aLEdvCwZkxVIZug+6OgsjSrTUHUaERHxOxq3EZMRutxQYXYGEajdybxHcn3o4QNloQLu9oWlqI+eI9YvwO8AFv7NBFLfG1e5PmRk6TdPKwhYt8Qsc1fgM9dE7x2eJqXKrspPVaVgQXfqsMbmjScpaMkTXVQTjhgjfwav10Db1d1KBGgguzE8MPC9TCOJz3hkjl6Bg/klH2XkQGLi2mRpS4TAIDw+Qd89PO3k+3YCFcLlK33jFNO/kO53PfvA7Aiw+qck39xYfMLC5WmP1W9fAwelj0WUD+EuEi7JzC2+NCfD8XpLYFO+CCuyKtl0tJ9JFMBFy4OUfEHFlxx7OCVfyWDT/hpWhc9B3c/PzPeOKdDS4j9wKsdeAeTjIzWqTZUehNtzBwYgbDJi5pVVfjyiJc0n/JDVBnJHw1TriAnbQIFzcf/KDmdEu+9DjZKO6AS1xFi+EI+rErEXDhA/detNEYXnsghW7JdjAypFfi8rcDLkuIAIEWgxfkMFouQlwuYCR2BGt9B5qPbLkIWQ8CgiHOXoiof0ozjuJNmr/DCA29zt2Qf7iuYnEB814IF2EfdoOi5Sz14Ja2xyWBFsv7JbNCERyT8LhozZx5NORmsm8Q3A0l0qOpcbloSoWLvgXSL16clKTeR4kphAu8vvhZElEEPqNUE5F38N87qn3azIAM4cI4IwdcPiDcFmR1d7mSmuKLU4a68LsEw1yMC9+Z9dmtLZDQwR6XQWQm3eWHuzsBlzhvipZRYR8V5rwNWzmMoQqXrZQ9LinIw3tZKgYgdRNYI1xS0kZcoq3vo5wvfJAGq/rf7OALjLXu0SYfjCDcBpdxnAEfQgN5NNpZ0AldDVL1M3xgXLinE6gp5Ys1XfnhgjoR+Rwi9j0cLm6xUDZCS9hSiEdNTrikFLgswUa9IB9/TKTkuHyWF7aTIuwtppCvSX3ekrTnxIhIy/nzb+l6LhkmI1KOLWFcRuRIwd+S1p/vrC4aZoDDSGgRIMRZDSq6BSgU2TjgEla4Lqi4ApeQsLjexRTXYEuhucruhMsFUypc3sNkRaMsfr4A0iEudcyloJsgtwtWwPIBXpj2qbr7XIehv22RiY2gzGDonbwoQ+N4LCafmvEi95DnmlEC+XEwOEa4tHNmcZXTgmrKB5cEmF7V+hTHGQch6vyaUdgjWoLs/Uxhis2m3sz34fIgZdv+rh0mXd+Gza+YC9EhIdtmuv6A8GI8UrfFAPNhRIoL6yjuG0Yj8p7GReOi6LDQdyf093Iht54BDYtw4UOUHvtvHA/IbHGJQhx6FZlAHyXiIqDP4pKxd1qYdTUudYaUuHyus5K35cGi6SLA4xgX6/I31XAHpqes7PQvKesSyHAxH6nH3klpaRl5T1d00Rxe7agKm3TCBXnmPPe79DJfvBKXITa2VJZqiwsKw5WnX5uLwwVVTnVMxhEX0FgKXALbIHlb4S5cD1PAAOECrr6oWvALLA3QF0BPQ6V+w8UYo+6LUrGOa8KwUkYvN1EWKlzQgTCHM0ZQUbT8Bq2dcBG6BahklXRFWo6LqkcrFpde+IlVlRv8LlwWYfsr3cWUFJdPqlkcFhcj/606VrhnWfyckuPCDKWt4Hnkg7y4LZyDauoY+YsmRTojhEEVvHbqjFTeZbAQ76LcRVwkLhmIi5Prc8ClTv6N647epY7BpS0/71JH+ralT200Lm1kmWlHzssFJu/AA8MqtYOqx5x3vUAeUvDShaZf83Av6Lwj/sGXNXZJwthF1RkVG7sg5ouOXdosKXBxbYNUZezysQ48D3Gpty7rdpWxCzCvo7MLfPytDYsCM7BFh8IkJmaXDRZNq1Tq/dJkIDC5tEXlPEk9nlLEw3gFTlFfIm8/Qgv5cRUuPqZ9RPnywcXjhoN8Ra8BJ2sLxgWxrIruHVh3wmW3jcZB1BcmPVAPLxXOKACT67n0qS0CzCdSt/spKTDsw/r9CxYw2w8ebKdSVK95n35YNsvsomZHHbdIYUvccalwQRMd4lqPJXTO1mHeJWQfVqFCCsUFeY+MYt6lPz9c2hS4TAuNyGhxW47LQ7n5MkwWvI8+tYt5oRp26YuEl9Q2X4n7v6WAdm6Sj7G4zTy0Ja0QWSZ0eFlGF/RD7hCeCFHhAqdnJDNmlpL5zeoO2Ma6aENcwbjAmWx3lXw+B68oKb6OwCd7XKagO6iXdy8PIR/1EJdGxIPUWke+SAKf/lF0L0aGN+vYwZMVKAuRSGDy5tbWl5uTdCU/cKMu+QfA676K7w8qihdTSOypwgX3cPK4oz0/XIKIY+kcImauUFxw5eTRfdgJl+l6SypcFuthutS96LswGeOCrqdk5pMoVep8PsHEPfb2zS8iMQrnxZTFP/RRbkfeBmRzfAS/GZN+4ZgSF4ygrCPBe9mcVqTRsH1AkklCKxoXvN1F5vvwtkwnXOpVS4wovX5NkrqPEgVcdmUr0nsoVfpLX2uUpwYmP3xpY5u+TUoj89AXjhbVaC1CNpcp38KAeiJ2BU+JSyf6BfeJcWo0nCcuZAOLGJV6h3AmBeOC/KTWLqlcyBmXRksqXFzLjVCS0c5UI9YKyO1SPbpxTcxqGiVOS0ta3IPJsqgUTQAhXlShN9JHoQtTDe4aCAvN0mgj0ky2NNFNp8QF72nR+viX3UXdqEEccUEbVdwCL4SWInAhlWvnTalDTUXjEthFAOzxvGCSKFzInWneSaziJPkoZQ3hInUDD+vaGNnzwlubUs0FUHvINJ/wk4v6qC+RiUbUuHTiviLM9kfMNlunvboICrd5xpVShDqUUgQuZGtVO/vroDaGOuLSqNyrS6DYY7qAwApFC8LlDHVrl+m+1q7hhFV4a4XtUh6idGk19F2u9T+pt+GRsJloW9l/eckmercWboqStvF6kwPUyVVu9KnGhdqVXTWAX9ThjbKb+J1wSYQwL+C0O7gbp4+rFoEL+XloVRmy4TvazFROicslS40BXSbTBFqYml7D7+lY3rtEC+HC3JxehOZ6YJXc3YPOJbB36WCZtPkiSpd0Y6Ym6zkA9lQA4NEeZftQDZd5PpV8T5oWHvJ3DQ4mk4PxAeY0O/9XHWxwIWcYzVP0wWQyEk3G2x3OGQkzIYOkE9RCPQ3JaDTZlWEPBBWDi3eAqtxAMBmNJJP+vvzOGSFcLl2Tad80WaTBONhfnpqaWl6taWTAQLjUsHcbr5nmy/sH9M1lWPSKaXBmdXltMeAKrK0g0qCjEnWzrZ7TtLRXm9zlzHY/TdnA4rL8C/3yf2G3JfhqM1xL2OGS6GcI1ML8obR8cKFPT4Njbxr/B5eKwQXvgYL5hvrcYuWUuJxR6xLoNtYuMXdramouCaYQl7NiHmc460NU8gG6c3Dt2gFJr1E27Scel/r6azwIgalplip5WM2rS3F0nfpahXlfO1zwhnvEGnOkNV9cuJOsbsavFLdmZCniXLlicDkDo4zlmhq1jZVUw+BiY31mH5W8IjJH5SSvq8hL4+4nqkNb2//SyCbzyw0qJUN2wBg/QXEOxRYX83CH+LoOkJf8DQwyXFSvcTBHcVaXUhwu6D1INpVT4lKjFsLFtXxGbQL+D3GptS6mD1T2OEeX60BucGBzWFtvlMmAYm/a1F5jvZC4rM6NU7xP0b5mI8imZOxxMU/Vy9rEfDVL3rgYw3xpw5pzRN+Di1k52YfVmqMJB1zO2gg37tqB3OBgba3W+gfEpdW62A+sys1rSetN1Uotrtm9CUKOi532bXLj5YlLXnFgvflgSLos7ICLy9sgZGdkZkRAiQJwcXkGhD8QqVkHEL8LF5e3S1a5pgRcVLLBpVYpgosrcGg0NmNqXNasBlxH4ArhYqXsu/T9WiHfs2cf0UPro0d8jrW1NY9sY9JlLr52UuOqXW6ivF3mWIiJb7Wq5h7FHgIDF+tdLPzWbio/fzsztDKG1eZURwI8R3CxLpUvSk32Mm/70LR280S2Mb6x/gYfshoCuchwASl87OX197GVC/WalfMAaxUu39S01NbSX/fat1Y2sfWb2foSXGoPrYy/cub/8B3D2iPO5Ou+4huDOiyMlkurhb+vNdrQ006NjDLBqKoVXZ7+KvNPbFY1qwxc5hsxh0hmYfh2yYRmPofXqPzWZcjmvbpRP1WnzCDAt9fNFN5j5VIl/lmUQZi9uJbgaciQbPvioHIeUDnF9qnAt1Ybsb/OoxWqeVsPj8BNYIlwsbRvXayt/EMA+3p4JGm7tRWKwa/79sNdY2hkF5ZLouri3u7r9UYGu8z3njY4vG3WC+WQXSToy/Q20bmxj+WTjTeRjPf09vqDEf4x51zs8vdGrcrFB1WV4xWwlWB8tH/46NG3w+XFAJuBLrlw6RJzTnpgbeXwm2kScGzcwLWCaFEPsSo6DTJwsRnG8UOsPEfQFf2/KnDtbN60nK057tpWdMwycMlfrcdd24qOW6vcwK3VZhLg0XFXtqLj1iFLxMraMj+4J8p/Orei/1OtEL9S27oK5vwCy4ffvj365+tXZg6ntbUS6Z56BWrhfFBt6yG3dTgQWPuqnjGq6FQKEPH125FsGueIxkW2Eb2iU6a1lZXlIyUJR8S/fPs3a1XRjylzReO/pr46LSdUVJHLXAe1cDk67npU9INobeWf/1YG0adL/wP/ipNYdHK0XgAAAABJRU5ErkJggg=="
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - grafana.example.com
          resources:
          - grafanacloudlogforwarders
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - grafana.example.com
          resources:
          - grafanacloudlogforwarders/finalizers
          verbs:
          - update
        - apiGroups:
          - grafana.example.com
          resources:
          - grafanacloudlogforwarders/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - logging.openshift.io
          resources:
          - clusterlogforwarders
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - logging.openshift.io
          resources:
          - clusterloggings
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: grafanacloud-operator-controller-manager
      deployments:
      - name: grafanacloud-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.7.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: quay.io/yoza/grafanacloud-operator:2.0.0
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 200m
                    memory: 100Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: grafanacloud-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: grafanacloud-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - clusterlogging
  - clusterlogforwarder
  - grafanacloudlogforwarder
  links:
  - name: Grafanacloud Operator
    url: https://grafanacloud-operator.domain
  maintainers:
  - email: yoza@redhat.com'
    name: '''Yash'
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.1
